// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: brittleSoil
			/// 2D
			/// </summary>
			public const string brittleSoil = "brittleSoil";

			/// <summary>
			/// Tag: buttonUI
			/// 2D
			/// </summary>
			public const string buttonUI = "buttonUI";

			/// <summary>
			/// Tag: caveWater
			/// 2D
			/// </summary>
			public const string caveWater = "caveWater";

			/// <summary>
			/// Tag: fireAbility
			/// 2D
			/// </summary>
			public const string fireAbility = "fireAbility";

			/// <summary>
			/// Tag: gameMusic
			/// 2D
			/// </summary>
			public const string gameMusic = "gameMusic";

			/// <summary>
			/// Tag: kappa
			/// 2D
			/// </summary>
			public const string kappa = "kappa";

			/// <summary>
			/// Tag: kappaEggs
			/// 2D
			/// </summary>
			public const string kappaEggs = "kappaEggs";

			/// <summary>
			/// Tag: playerAttack
			/// 2D
			/// </summary>
			public const string playerAttack = "playerAttack";

			/// <summary>
			/// Tag: playerState
			/// 2D
			/// </summary>
			public const string playerState = "playerState";

			/// <summary>
			/// Tag: saveGame
			/// 2D
			/// </summary>
			public const string saveGame = "saveGame";

			/// <summary>
			/// Tag: stalactite
			/// 2D
			/// </summary>
			public const string stalactite = "stalactite";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: abilityAction
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string abilityAction = "abilityAction";

			/// <summary>
			/// Variable: attack
			/// Range: [0 - 2]
			/// Type: Global
			/// </summary>
			public const string attack = "attack";

			/// <summary>
			/// Variable: interactionUI
			/// Range: [0 - 1]
			/// Type: Global
			/// </summary>
			public const string interactionUI = "interactionUI";

			/// <summary>
			/// Variable: kappaAction
			/// Range: [0 - 5]
			/// Type: Local
			/// </summary>
			public const string kappaAction = "kappaAction";

			/// <summary>
			/// Variable: playerState
			/// Range: [0 - 6]
			/// Type: Global
			/// </summary>
			public const string playerState = "playerState";

			/// <summary>
			/// Variable: scene
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string scene = "scene";

			/// <summary>
			/// Variable: stalactiteState
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string stalactiteState = "stalactiteState";

		}

		public class Channels
		{
			public const string Master = "Master";

			public const string Music = "Music";

			public const string SFX = "SFX";

		}
	}
}
